apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "node-init.fullname" . }}
  labels:
    app: "{{ template "node-init.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "node-init.fullname" . }}
      name: {{ template "node-init.fullname" . }}
      annotations:
        checksum/configmaps: {{ tpl (toYaml .Values.configMaps) . | sha256sum }}
        checksum/secrets: {{ tpl (toYaml .Values.secrets) . | sha256sum }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 1
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.useHostNetwork }}
      hostNetwork: {{ .Values.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.useHostPID }}
      hostPID: {{ .Values.useHostPID }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
      - name: {{ default .Chart.Name .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/bash
        - /var/node-init/run
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{{ include "node-init.env" . | indent 8 }}
        volumeMounts:
        - name: host-var
          mountPath: /host/var/
        {{ if .Values.sysctl.enabled -}}
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        {{- end }}
{{ include "node-init.files.volumeMounts" . | indent 8 }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
{{- end }}
      volumes:
      - name: host-var
        hostPath:
          path: /var
          type: Directory
      {{ if .Values.sysctl.enabled -}}
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory
      {{- end }}
{{ include "node-init.files.volumes" . | indent 6 }}
{{ toYaml .Values.volumes | indent 6 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "node-init.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
  updateStrategy:
    type: {{ default "OnDelete" .Values.updateStrategy | quote }}
